# .goreleaser.yml
builds:
  - id: mailrestapi
    binary: mailrestapi
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd    
    goarch:
      - amd64
      - arm64
      - riscv64
      - s390x
      - ppc64le
      - mips64le
      - mips64
      - mips
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# Only include the executable, no additional files
archives:
  - format: tar.zst
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - mailrestapi*
