# .goreleaser.yml
builds:
  - id: mailrestapi
    binary: mailrestapi
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd    
    goarch:
      - amd64
      - arm64
      - riscv64
      - s390x
      - ppc64le
      - mips64le
      - mips64
      - mips
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# Only include the executable, no additional files
archives:
  # Linux archives with service file
  - id: linux
    format: tar.zst
    builds:
      - mailrestapi
    goos:
      - linux
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - mailrestapi*
      - "linux/systemd/mailrestapi.service"
  
  # Other platforms - executable only
  - id: others
    format: tar.zst
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - mailrestapi
    goos:
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - mailrestapi*
